kind: InvokeWatsonxModels
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeWatsonxModels-1jyqy
  namespace: Finance-OAuth-LLM
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  region: us-south
  opVersion: placeholder-op-version
  tlsClientProfile: tls-client-profile-default:1.0.0
  inputMessage: request
  outputMessage: response
  cachePolicy: disabled
