kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: plan-finance-llm-oauth-1jyqy
  namespace: Finance-OAuth-LLM
  version: '1.0'
  tags: []
  description: ''
  domain: ai-platform
spec:
  qos:
    withQuota:
      watsonx-token-weighted:
        - $ref: Finance-OAuth-LLM:watsonx-token-weighted-1jyqy:1.0
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: Finance-OAuth-LLM:api-finance-llm-oauth-1jyqy:1.0
            operations:
              - path: /deployment-models
                method: get
              - path: /text-generate
                method: post
              - path: /tokenize
                method: post
        telemetry: {}
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: Finance-OAuth-LLM:api-finance-llm-oauth-1jyqy:1.0
            operations:
              - path: /deployment-models
                method: get
              - path: /text-generate
                method: post
              - path: /tokenize
                method: post
