kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: Telemetry-1jyqy
  namespace: Finance-OAuth-LLM
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: basic
      onSuccessTrimTo: normal
      inboundLevel: basic
      outboundLevel: basic
      operations:
        - path: /deployment-models
          method: GET
        - path: /text-generate
          method: POST
        - path: /tokenize
          method: POST
