kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: api-watsonx-loan-llm-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  domain: ai-platform
spec:
  api-spec:
    $path: ./api-spec-b1qhj.yml
  policy-sequence:
    - $ref: Loans-Service:freeflowpolicysequence-watsonx-loan-llm-b1qhj:1.0
