kind: Authorize
apiVersion: api.ibm.com/v1
metadata:
  name: Authorize-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  operation:
    subscription: {}
  namespace: client
