kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  namespace: client
  operation:
    subscription: {}
