kind: ExtractIdentity
apiVersion: api.ibm.com/v1
metadata:
  name: ExtractIdentity-KmRlP
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  namespace: Loans-Service
  credentialType:
    apiKey:
      clientId:
        httpHeader:
          name: X-IBM-Client-Id
      clientSecret:
        httpHeader:
          name: X-IBM-Client-Secret
