kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-y9x3j
  namespace: loan-service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: tls-client-profile-default:1.0.0
        url: >-
          'https://loan-service.2cdce5chee35.au-syd.codeengine.appdomain.cloud'
          & $pathAndQuery()
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: true
        followRedirects: false
        chunkedUpload: false
