kind: OperationSwitch
apiVersion: api.ibm.com/v1
metadata:
  name: OperationSwitch-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - conditions:
        - verbPath:
            path: /deployment-models
            verb: GET
      execute:
        - $ref: Loans-Service:InvokeWatsonxModels-b1qhj:1.0
    - conditions:
        - verbPath:
            path: /text-generate
            verb: POST
      execute:
        - $ref: Loans-Service:InvokeWatsonxTextGen-b1qhj:1.0
    - conditions:
        - verbPath:
            path: /tokenize
            verb: POST
      execute:
        - $ref: Loans-Service:InvokeWatsonxTokenize-b1qhj:1.0
