kind: Parse
apiVersion: api.ibm.com/v1
metadata:
  name: Parse-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  documentType:
    json: {}
  input: request
