kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-token-weighted-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  description: ''
spec:
  maxRequest: 1000
  interval: 1s
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: $variable('aiGeneratedTokenCount')
        exceedAction: continue
        intervalOffset: 0
        dynamicValue: ''
