kind: Throw
apiVersion: api.ibm.com/v1
metadata:
  name: Throw-b1qhj
  namespace: Loans-Service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  error:
    CustomError:
      message: An error occurred while processing your request.
      messageType: plain
      status: 400
